export const FETCH_POKEMON = 'FETCH_POKEMON';
export const COUNT_POKEMON = 'COUNT_POKEMON';
export const POKEMON_TYPE = 'POKEMON_TYPE';
export const UPDATE_OFFSET = 'UPDATE_OFFSET';
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS';
export const UPDATE_ACTIVE_PAGE = 'UPDATE_ACTIVE_PAGE';